import Head from 'next/head'
import { client } from '../../lib/client';
import HeroBanner from '../components/HeroBanner'

export default function Home({products, banner}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner heroBanner={banner.length && banner[0]}/>

      <div className='products-heading'>
        <h2>Loja do juan</h2>
        <p>Muita comida boa</p>
      </div>

      <div className='products-container'>
        {products?.map((p) => p.name)}
      </div>
    
    </>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const banner = await client.fetch(bannerQuery);

  return {
    props: { products , banner }
  }
}